// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarWarsUniverse.Data;

namespace StarWarsUniverse.Data.Migrations
{
    [DbContext(typeof(StarWarsContext))]
    [Migration("20201012153121_RatingToMovie")]
    partial class RatingToMovie
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("StarWarsUniverse.Domain.Movie", b =>
                {
                    b.Property<string>("Uri")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Edited")
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpeningCrawl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Producer")
                        .HasColumnType("TEXT");

                    b.Property<float>("Rating")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Uri");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Uri = "http://swapi.dev/api/films/1/",
                            Created = new DateTime(2014, 12, 10, 14, 23, 31, 880, DateTimeKind.Utc),
                            Director = "George Lucas",
                            Edited = new DateTime(2014, 12, 20, 19, 49, 45, 256, DateTimeKind.Utc),
                            EpisodeId = 4,
                            OpeningCrawl = @"It is a period of civil war.
Rebel spaceships, striking
from a hidden base, have won
their first victory against
the evil Galactic Empire.

During the battle, Rebel
spies managed to steal secret
plans to the Empire's
ultimate weapon, the DEATH
STAR, an armored space
station with enough power
to destroy an entire planet.

Pursued by the Empire's
sinister agents, Princess
Leia races home aboard her
starship, custodian of the
stolen plans that can save her
people and restore
freedom to the galaxy....",
                            Producer = "Gary Kurtz, Rick McCallum",
                            Rating = 0f,
                            ReleaseDate = new DateTime(1977, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "A New Hope"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/films/2/",
                            Created = new DateTime(2014, 12, 12, 11, 26, 24, 656, DateTimeKind.Utc),
                            Director = "Irvin Kershner",
                            Edited = new DateTime(2014, 12, 15, 13, 7, 53, 386, DateTimeKind.Utc),
                            EpisodeId = 5,
                            OpeningCrawl = @"It is a dark time for the
Rebellion. Although the Death
Star has been destroyed,
Imperial troops have driven the
Rebel forces from their hidden
base and pursued them across
the galaxy.

Evading the dreaded Imperial
Starfleet, a group of freedom
fighters led by Luke Skywalker
has established a new secret
base on the remote ice world
of Hoth.

The evil lord Darth Vader,
obsessed with finding young
Skywalker, has dispatched
thousands of remote probes into
the far reaches of space....",
                            Producer = "Gary Kurtz, Rick McCallum",
                            Rating = 0f,
                            ReleaseDate = new DateTime(1980, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Empire Strikes Back"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/films/3/",
                            Created = new DateTime(2014, 12, 18, 10, 39, 33, 255, DateTimeKind.Utc),
                            Director = "Richard Marquand",
                            Edited = new DateTime(2014, 12, 20, 9, 48, 37, 462, DateTimeKind.Utc),
                            EpisodeId = 6,
                            OpeningCrawl = @"Luke Skywalker has returned to
his home planet of Tatooine in
an attempt to rescue his
friend Han Solo from the
clutches of the vile gangster
Jabba the Hutt.

Little does Luke know that the
GALACTIC EMPIRE has secretly
begun construction on a new
armored space station even
more powerful than the first
dreaded Death Star.

When completed, this ultimate
weapon will spell certain doom
for the small band of rebels
struggling to restore freedom
to the galaxy...",
                            Producer = "Howard G. Kazanjian, George Lucas, Rick McCallum",
                            Rating = 0f,
                            ReleaseDate = new DateTime(1983, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Return of the Jedi"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/films/4/",
                            Created = new DateTime(2014, 12, 19, 16, 52, 55, 740, DateTimeKind.Utc),
                            Director = "George Lucas",
                            Edited = new DateTime(2014, 12, 20, 10, 54, 7, 216, DateTimeKind.Utc),
                            EpisodeId = 1,
                            OpeningCrawl = @"Turmoil has engulfed the
Galactic Republic. The taxation
of trade routes to outlying star
systems is in dispute.

Hoping to resolve the matter
with a blockade of deadly
battleships, the greedy Trade
Federation has stopped all
shipping to the small planet
of Naboo.

While the Congress of the
Republic endlessly debates
this alarming chain of events,
the Supreme Chancellor has
secretly dispatched two Jedi
Knights, the guardians of
peace and justice in the
galaxy, to settle the conflict....",
                            Producer = "Rick McCallum",
                            Rating = 0f,
                            ReleaseDate = new DateTime(1999, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Phantom Menace"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/films/5/",
                            Created = new DateTime(2014, 12, 20, 10, 57, 57, 886, DateTimeKind.Utc),
                            Director = "George Lucas",
                            Edited = new DateTime(2014, 12, 20, 20, 18, 48, 516, DateTimeKind.Utc),
                            EpisodeId = 2,
                            OpeningCrawl = @"There is unrest in the Galactic
Senate. Several thousand solar
systems have declared their
intentions to leave the Republic.

This separatist movement,
under the leadership of the
mysterious Count Dooku, has
made it difficult for the limited
number of Jedi Knights to maintain 
peace and order in the galaxy.

Senator Amidala, the former
Queen of Naboo, is returning
to the Galactic Senate to vote
on the critical issue of creating
an ARMY OF THE REPUBLIC
to assist the overwhelmed
Jedi....",
                            Producer = "Rick McCallum",
                            Rating = 0f,
                            ReleaseDate = new DateTime(2002, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Attack of the Clones"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/films/6/",
                            Created = new DateTime(2014, 12, 20, 18, 49, 38, 403, DateTimeKind.Utc),
                            Director = "George Lucas",
                            Edited = new DateTime(2014, 12, 20, 20, 47, 52, 73, DateTimeKind.Utc),
                            EpisodeId = 3,
                            OpeningCrawl = @"War! The Republic is crumbling
under attacks by the ruthless
Sith Lord, Count Dooku.
There are heroes on both sides.
Evil is everywhere.

In a stunning move, the
fiendish droid leader, General
Grievous, has swept into the
Republic capital and kidnapped
Chancellor Palpatine, leader of
the Galactic Senate.

As the Separatist Droid Army
attempts to flee the besieged
capital with their valuable
hostage, two Jedi Knights lead a
desperate mission to rescue the
captive Chancellor....",
                            Producer = "Rick McCallum",
                            Rating = 0f,
                            ReleaseDate = new DateTime(2005, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Revenge of the Sith"
                        });
                });

            modelBuilder.Entity("StarWarsUniverse.Domain.MoviePlanet", b =>
                {
                    b.Property<string>("MovieUri")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanetUri")
                        .HasColumnType("TEXT");

                    b.HasKey("MovieUri", "PlanetUri");

                    b.HasIndex("PlanetUri");

                    b.ToTable("MoviePlanet");

                    b.HasData(
                        new
                        {
                            MovieUri = "http://swapi.dev/api/films/1/",
                            PlanetUri = "http://swapi.dev/api/planets/1/"
                        },
                        new
                        {
                            MovieUri = "http://swapi.dev/api/films/1/",
                            PlanetUri = "http://swapi.dev/api/planets/2/"
                        },
                        new
                        {
                            MovieUri = "http://swapi.dev/api/films/1/",
                            PlanetUri = "http://swapi.dev/api/planets/3/"
                        },
                        new
                        {
                            MovieUri = "http://swapi.dev/api/films/2/",
                            PlanetUri = "http://swapi.dev/api/planets/4/"
                        },
                        new
                        {
                            MovieUri = "http://swapi.dev/api/films/2/",
                            PlanetUri = "http://swapi.dev/api/planets/5/"
                        },
                        new
                        {
                            MovieUri = "http://swapi.dev/api/films/2/",
                            PlanetUri = "http://swapi.dev/api/planets/6/"
                        },
                        new
                        {
                            MovieUri = "http://swapi.dev/api/films/2/",
                            PlanetUri = "http://swapi.dev/api/planets/27/"
                        },
                        new
                        {
                            MovieUri = "http://swapi.dev/api/films/3/",
                            PlanetUri = "http://swapi.dev/api/planets/1/"
                        },
                        new
                        {
                            MovieUri = "http://swapi.dev/api/films/3/",
                            PlanetUri = "http://swapi.dev/api/planets/5/"
                        },
                        new
                        {
                            MovieUri = "http://swapi.dev/api/films/3/",
                            PlanetUri = "http://swapi.dev/api/planets/7/"
                        },
                        new
                        {
                            MovieUri = "http://swapi.dev/api/films/3/",
                            PlanetUri = "http://swapi.dev/api/planets/8/"
                        },
                        new
                        {
                            MovieUri = "http://swapi.dev/api/films/3/",
                            PlanetUri = "http://swapi.dev/api/planets/9/"
                        },
                        new
                        {
                            MovieUri = "http://swapi.dev/api/films/4/",
                            PlanetUri = "http://swapi.dev/api/planets/1/"
                        },
                        new
                        {
                            MovieUri = "http://swapi.dev/api/films/4/",
                            PlanetUri = "http://swapi.dev/api/planets/8/"
                        },
                        new
                        {
                            MovieUri = "http://swapi.dev/api/films/4/",
                            PlanetUri = "http://swapi.dev/api/planets/9/"
                        },
                        new
                        {
                            MovieUri = "http://swapi.dev/api/films/5/",
                            PlanetUri = "http://swapi.dev/api/planets/1/"
                        },
                        new
                        {
                            MovieUri = "http://swapi.dev/api/films/5/",
                            PlanetUri = "http://swapi.dev/api/planets/8/"
                        },
                        new
                        {
                            MovieUri = "http://swapi.dev/api/films/5/",
                            PlanetUri = "http://swapi.dev/api/planets/9/"
                        },
                        new
                        {
                            MovieUri = "http://swapi.dev/api/films/5/",
                            PlanetUri = "http://swapi.dev/api/planets/10/"
                        },
                        new
                        {
                            MovieUri = "http://swapi.dev/api/films/5/",
                            PlanetUri = "http://swapi.dev/api/planets/11/"
                        },
                        new
                        {
                            MovieUri = "http://swapi.dev/api/films/6/",
                            PlanetUri = "http://swapi.dev/api/planets/1/"
                        },
                        new
                        {
                            MovieUri = "http://swapi.dev/api/films/6/",
                            PlanetUri = "http://swapi.dev/api/planets/2/"
                        },
                        new
                        {
                            MovieUri = "http://swapi.dev/api/films/6/",
                            PlanetUri = "http://swapi.dev/api/planets/5/"
                        },
                        new
                        {
                            MovieUri = "http://swapi.dev/api/films/6/",
                            PlanetUri = "http://swapi.dev/api/planets/8/"
                        },
                        new
                        {
                            MovieUri = "http://swapi.dev/api/films/6/",
                            PlanetUri = "http://swapi.dev/api/planets/9/"
                        },
                        new
                        {
                            MovieUri = "http://swapi.dev/api/films/6/",
                            PlanetUri = "http://swapi.dev/api/planets/12/"
                        },
                        new
                        {
                            MovieUri = "http://swapi.dev/api/films/6/",
                            PlanetUri = "http://swapi.dev/api/planets/13/"
                        },
                        new
                        {
                            MovieUri = "http://swapi.dev/api/films/6/",
                            PlanetUri = "http://swapi.dev/api/planets/14/"
                        },
                        new
                        {
                            MovieUri = "http://swapi.dev/api/films/6/",
                            PlanetUri = "http://swapi.dev/api/planets/15/"
                        },
                        new
                        {
                            MovieUri = "http://swapi.dev/api/films/6/",
                            PlanetUri = "http://swapi.dev/api/planets/16/"
                        },
                        new
                        {
                            MovieUri = "http://swapi.dev/api/films/6/",
                            PlanetUri = "http://swapi.dev/api/planets/17/"
                        },
                        new
                        {
                            MovieUri = "http://swapi.dev/api/films/6/",
                            PlanetUri = "http://swapi.dev/api/planets/18/"
                        },
                        new
                        {
                            MovieUri = "http://swapi.dev/api/films/6/",
                            PlanetUri = "http://swapi.dev/api/planets/19/"
                        });
                });

            modelBuilder.Entity("StarWarsUniverse.Domain.Planet", b =>
                {
                    b.Property<string>("Uri")
                        .HasColumnType("TEXT");

                    b.Property<string>("Climate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diameter")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Edited")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gravity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrbitalPeriod")
                        .HasColumnType("TEXT");

                    b.Property<string>("Population")
                        .HasColumnType("TEXT");

                    b.Property<string>("RotationPeriod")
                        .HasColumnType("TEXT");

                    b.Property<string>("SurfaceWater")
                        .HasColumnType("TEXT");

                    b.Property<string>("Terrain")
                        .HasColumnType("TEXT");

                    b.HasKey("Uri");

                    b.ToTable("Planets");

                    b.HasData(
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/1/",
                            Climate = "arid",
                            Created = new DateTime(2014, 12, 9, 13, 50, 49, 641, DateTimeKind.Utc),
                            Diameter = "10465",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 411, DateTimeKind.Utc),
                            Gravity = "1 standard",
                            Name = "Tatooine",
                            OrbitalPeriod = "304",
                            Population = "200000",
                            RotationPeriod = "23",
                            SurfaceWater = "1",
                            Terrain = "desert"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/2/",
                            Climate = "temperate",
                            Created = new DateTime(2014, 12, 10, 11, 35, 48, 479, DateTimeKind.Utc),
                            Diameter = "12500",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 420, DateTimeKind.Utc),
                            Gravity = "1 standard",
                            Name = "Alderaan",
                            OrbitalPeriod = "364",
                            Population = "2000000000",
                            RotationPeriod = "24",
                            SurfaceWater = "40",
                            Terrain = "grasslands, mountains"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/3/",
                            Climate = "temperate, tropical",
                            Created = new DateTime(2014, 12, 10, 11, 37, 19, 144, DateTimeKind.Utc),
                            Diameter = "10200",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 421, DateTimeKind.Utc),
                            Gravity = "1 standard",
                            Name = "Yavin IV",
                            OrbitalPeriod = "4818",
                            Population = "1000",
                            RotationPeriod = "24",
                            SurfaceWater = "8",
                            Terrain = "jungle, rainforests"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/4/",
                            Climate = "frozen",
                            Created = new DateTime(2014, 12, 10, 11, 39, 13, 934, DateTimeKind.Utc),
                            Diameter = "7200",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 423, DateTimeKind.Utc),
                            Gravity = "1.1 standard",
                            Name = "Hoth",
                            OrbitalPeriod = "549",
                            Population = "unknown",
                            RotationPeriod = "23",
                            SurfaceWater = "100",
                            Terrain = "tundra, ice caves, mountain ranges"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/5/",
                            Climate = "murky",
                            Created = new DateTime(2014, 12, 10, 11, 42, 22, 590, DateTimeKind.Utc),
                            Diameter = "8900",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 425, DateTimeKind.Utc),
                            Gravity = "N/A",
                            Name = "Dagobah",
                            OrbitalPeriod = "341",
                            Population = "unknown",
                            RotationPeriod = "23",
                            SurfaceWater = "8",
                            Terrain = "swamp, jungles"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/6/",
                            Climate = "temperate",
                            Created = new DateTime(2014, 12, 10, 11, 43, 55, 240, DateTimeKind.Utc),
                            Diameter = "118000",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 427, DateTimeKind.Utc),
                            Gravity = "1.5 (surface), 1 standard (Cloud City)",
                            Name = "Bespin",
                            OrbitalPeriod = "5110",
                            Population = "6000000",
                            RotationPeriod = "12",
                            SurfaceWater = "0",
                            Terrain = "gas giant"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/7/",
                            Climate = "temperate",
                            Created = new DateTime(2014, 12, 10, 11, 50, 29, 349, DateTimeKind.Utc),
                            Diameter = "4900",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 429, DateTimeKind.Utc),
                            Gravity = "0.85 standard",
                            Name = "Endor",
                            OrbitalPeriod = "402",
                            Population = "30000000",
                            RotationPeriod = "18",
                            SurfaceWater = "8",
                            Terrain = "forests, mountains, lakes"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/8/",
                            Climate = "temperate",
                            Created = new DateTime(2014, 12, 10, 11, 52, 31, 66, DateTimeKind.Utc),
                            Diameter = "12120",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 430, DateTimeKind.Utc),
                            Gravity = "1 standard",
                            Name = "Naboo",
                            OrbitalPeriod = "312",
                            Population = "4500000000",
                            RotationPeriod = "26",
                            SurfaceWater = "12",
                            Terrain = "grassy hills, swamps, forests, mountains"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/9/",
                            Climate = "temperate",
                            Created = new DateTime(2014, 12, 10, 11, 54, 13, 921, DateTimeKind.Utc),
                            Diameter = "12240",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 432, DateTimeKind.Utc),
                            Gravity = "1 standard",
                            Name = "Coruscant",
                            OrbitalPeriod = "368",
                            Population = "1000000000000",
                            RotationPeriod = "24",
                            SurfaceWater = "unknown",
                            Terrain = "cityscape, mountains"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/10/",
                            Climate = "temperate",
                            Created = new DateTime(2014, 12, 10, 12, 45, 6, 577, DateTimeKind.Utc),
                            Diameter = "19720",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 434, DateTimeKind.Utc),
                            Gravity = "1 standard",
                            Name = "Kamino",
                            OrbitalPeriod = "463",
                            Population = "1000000000",
                            RotationPeriod = "27",
                            SurfaceWater = "100",
                            Terrain = "ocean"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/11/",
                            Climate = "temperate, arid",
                            Created = new DateTime(2014, 12, 10, 12, 47, 22, 350, DateTimeKind.Utc),
                            Diameter = "11370",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 437, DateTimeKind.Utc),
                            Gravity = "0.9 standard",
                            Name = "Geonosis",
                            OrbitalPeriod = "256",
                            Population = "100000000000",
                            RotationPeriod = "30",
                            SurfaceWater = "5",
                            Terrain = "rock, desert, mountain, barren"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/12/",
                            Climate = "temperate, arid, windy",
                            Created = new DateTime(2014, 12, 10, 12, 49, 1, 491, DateTimeKind.Utc),
                            Diameter = "12900",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 439, DateTimeKind.Utc),
                            Gravity = "1 standard",
                            Name = "Utapau",
                            OrbitalPeriod = "351",
                            Population = "95000000",
                            RotationPeriod = "27",
                            SurfaceWater = "0.9",
                            Terrain = "scrublands, savanna, canyons, sinkholes"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/13/",
                            Climate = "hot",
                            Created = new DateTime(2014, 12, 10, 12, 50, 16, 526, DateTimeKind.Utc),
                            Diameter = "4200",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 440, DateTimeKind.Utc),
                            Gravity = "1 standard",
                            Name = "Mustafar",
                            OrbitalPeriod = "412",
                            Population = "20000",
                            RotationPeriod = "36",
                            SurfaceWater = "0",
                            Terrain = "volcanoes, lava rivers, mountains, caves"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/14/",
                            Climate = "tropical",
                            Created = new DateTime(2014, 12, 10, 13, 32, 0, 124, DateTimeKind.Utc),
                            Diameter = "12765",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 442, DateTimeKind.Utc),
                            Gravity = "1 standard",
                            Name = "Kashyyyk",
                            OrbitalPeriod = "381",
                            Population = "45000000",
                            RotationPeriod = "26",
                            SurfaceWater = "60",
                            Terrain = "jungle, forests, lakes, rivers"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/15/",
                            Climate = "artificial temperate ",
                            Created = new DateTime(2014, 12, 10, 13, 33, 46, 405, DateTimeKind.Utc),
                            Diameter = "0",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 444, DateTimeKind.Utc),
                            Gravity = "0.56 standard",
                            Name = "Polis Massa",
                            OrbitalPeriod = "590",
                            Population = "1000000",
                            RotationPeriod = "24",
                            SurfaceWater = "0",
                            Terrain = "airless asteroid"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/16/",
                            Climate = "frigid",
                            Created = new DateTime(2014, 12, 10, 13, 43, 39, 139, DateTimeKind.Utc),
                            Diameter = "10088",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 446, DateTimeKind.Utc),
                            Gravity = "1 standard",
                            Name = "Mygeeto",
                            OrbitalPeriod = "167",
                            Population = "19000000",
                            RotationPeriod = "12",
                            SurfaceWater = "unknown",
                            Terrain = "glaciers, mountains, ice canyons"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/17/",
                            Climate = "hot, humid",
                            Created = new DateTime(2014, 12, 10, 13, 44, 50, 397, DateTimeKind.Utc),
                            Diameter = "9100",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 447, DateTimeKind.Utc),
                            Gravity = "0.75 standard",
                            Name = "Felucia",
                            OrbitalPeriod = "231",
                            Population = "8500000",
                            RotationPeriod = "34",
                            SurfaceWater = "unknown",
                            Terrain = "fungus forests"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/18/",
                            Climate = "temperate, moist",
                            Created = new DateTime(2014, 12, 10, 13, 46, 28, 704, DateTimeKind.Utc),
                            Diameter = "0",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 449, DateTimeKind.Utc),
                            Gravity = "1 standard",
                            Name = "Cato Neimoidia",
                            OrbitalPeriod = "278",
                            Population = "10000000",
                            RotationPeriod = "25",
                            SurfaceWater = "unknown",
                            Terrain = "mountains, fields, forests, rock arches"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/19/",
                            Climate = "hot",
                            Created = new DateTime(2014, 12, 10, 13, 47, 46, 874, DateTimeKind.Utc),
                            Diameter = "14920",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 450, DateTimeKind.Utc),
                            Gravity = "unknown",
                            Name = "Saleucami",
                            OrbitalPeriod = "392",
                            Population = "1400000000",
                            RotationPeriod = "26",
                            SurfaceWater = "unknown",
                            Terrain = "caves, desert, mountains, volcanoes"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/20/",
                            Climate = "temperate",
                            Created = new DateTime(2014, 12, 10, 16, 16, 26, 566, DateTimeKind.Utc),
                            Diameter = "0",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 452, DateTimeKind.Utc),
                            Gravity = "1 standard",
                            Name = "Stewjon",
                            OrbitalPeriod = "unknown",
                            Population = "unknown",
                            RotationPeriod = "unknown",
                            SurfaceWater = "unknown",
                            Terrain = "grass"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/21/",
                            Climate = "polluted",
                            Created = new DateTime(2014, 12, 10, 16, 26, 54, 384, DateTimeKind.Utc),
                            Diameter = "13490",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 454, DateTimeKind.Utc),
                            Gravity = "1 standard",
                            Name = "Eriadu",
                            OrbitalPeriod = "360",
                            Population = "22000000000",
                            RotationPeriod = "24",
                            SurfaceWater = "unknown",
                            Terrain = "cityscape"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/22/",
                            Climate = "temperate",
                            Created = new DateTime(2014, 12, 10, 16, 49, 12, 453, DateTimeKind.Utc),
                            Diameter = "11000",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 456, DateTimeKind.Utc),
                            Gravity = "1 standard",
                            Name = "Corellia",
                            OrbitalPeriod = "329",
                            Population = "3000000000",
                            RotationPeriod = "25",
                            SurfaceWater = "70",
                            Terrain = "plains, urban, hills, forests"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/23/",
                            Climate = "hot",
                            Created = new DateTime(2014, 12, 10, 17, 3, 28, 110, DateTimeKind.Utc),
                            Diameter = "7549",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 458, DateTimeKind.Utc),
                            Gravity = "1 standard",
                            Name = "Rodia",
                            OrbitalPeriod = "305",
                            Population = "1300000000",
                            RotationPeriod = "29",
                            SurfaceWater = "60",
                            Terrain = "jungles, oceans, urban, swamps"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/24/",
                            Climate = "temperate",
                            Created = new DateTime(2014, 12, 10, 17, 11, 29, 452, DateTimeKind.Utc),
                            Diameter = "12150",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 460, DateTimeKind.Utc),
                            Gravity = "1 standard",
                            Name = "Nal Hutta",
                            OrbitalPeriod = "413",
                            Population = "7000000000",
                            RotationPeriod = "87",
                            SurfaceWater = "unknown",
                            Terrain = "urban, oceans, swamps, bogs"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/25/",
                            Climate = "temperate",
                            Created = new DateTime(2014, 12, 10, 17, 23, 29, 896, DateTimeKind.Utc),
                            Diameter = "9830",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 461, DateTimeKind.Utc),
                            Gravity = "1 standard",
                            Name = "Dantooine",
                            OrbitalPeriod = "378",
                            Population = "1000",
                            RotationPeriod = "25",
                            SurfaceWater = "unknown",
                            Terrain = "oceans, savannas, mountains, grasslands"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/26/",
                            Climate = "temperate",
                            Created = new DateTime(2014, 12, 12, 11, 16, 55, 78, DateTimeKind.Utc),
                            Diameter = "6400",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 463, DateTimeKind.Utc),
                            Gravity = "unknown",
                            Name = "Bestine IV",
                            OrbitalPeriod = "680",
                            Population = "62000000",
                            RotationPeriod = "26",
                            SurfaceWater = "98",
                            Terrain = "rocky islands, oceans"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/27/",
                            Climate = "temperate",
                            Created = new DateTime(2014, 12, 15, 12, 23, 41, 661, DateTimeKind.Utc),
                            Diameter = "14050",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 464, DateTimeKind.Utc),
                            Gravity = "1 standard",
                            Name = "Ord Mantell",
                            OrbitalPeriod = "334",
                            Population = "4000000000",
                            RotationPeriod = "26",
                            SurfaceWater = "10",
                            Terrain = "plains, seas, mesas"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/28/",
                            Climate = "unknown",
                            Created = new DateTime(2014, 12, 15, 12, 25, 59, 569, DateTimeKind.Utc),
                            Diameter = "0",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 466, DateTimeKind.Utc),
                            Gravity = "unknown",
                            Name = "unknown",
                            OrbitalPeriod = "0",
                            Population = "unknown",
                            RotationPeriod = "0",
                            SurfaceWater = "unknown",
                            Terrain = "unknown"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/29/",
                            Climate = "arid",
                            Created = new DateTime(2014, 12, 15, 12, 53, 47, 695, DateTimeKind.Utc),
                            Diameter = "0",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 468, DateTimeKind.Utc),
                            Gravity = "0.62 standard",
                            Name = "Trandosha",
                            OrbitalPeriod = "371",
                            Population = "42000000",
                            RotationPeriod = "25",
                            SurfaceWater = "unknown",
                            Terrain = "mountains, seas, grasslands, deserts"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/30/",
                            Climate = "arid",
                            Created = new DateTime(2014, 12, 15, 12, 56, 31, 121, DateTimeKind.Utc),
                            Diameter = "0",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 469, DateTimeKind.Utc),
                            Gravity = "1 standard",
                            Name = "Socorro",
                            OrbitalPeriod = "326",
                            Population = "300000000",
                            RotationPeriod = "20",
                            SurfaceWater = "unknown",
                            Terrain = "deserts, mountains"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/31/",
                            Climate = "temperate",
                            Created = new DateTime(2014, 12, 18, 11, 7, 1, 792, DateTimeKind.Utc),
                            Diameter = "11030",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 471, DateTimeKind.Utc),
                            Gravity = "1",
                            Name = "Mon Cala",
                            OrbitalPeriod = "398",
                            Population = "27000000000",
                            RotationPeriod = "21",
                            SurfaceWater = "100",
                            Terrain = "oceans, reefs, islands"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/32/",
                            Climate = "temperate",
                            Created = new DateTime(2014, 12, 18, 11, 11, 51, 872, DateTimeKind.Utc),
                            Diameter = "13500",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 472, DateTimeKind.Utc),
                            Gravity = "1",
                            Name = "Chandrila",
                            OrbitalPeriod = "368",
                            Population = "1200000000",
                            RotationPeriod = "20",
                            SurfaceWater = "40",
                            Terrain = "plains, forests"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/33/",
                            Climate = "superheated",
                            Created = new DateTime(2014, 12, 18, 11, 25, 40, 243, DateTimeKind.Utc),
                            Diameter = "12780",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 474, DateTimeKind.Utc),
                            Gravity = "1",
                            Name = "Sullust",
                            OrbitalPeriod = "263",
                            Population = "18500000000",
                            RotationPeriod = "20",
                            SurfaceWater = "5",
                            Terrain = "mountains, volcanoes, rocky deserts"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/34/",
                            Climate = "temperate",
                            Created = new DateTime(2014, 12, 19, 17, 47, 54, 403, DateTimeKind.Utc),
                            Diameter = "7900",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 476, DateTimeKind.Utc),
                            Gravity = "1",
                            Name = "Toydaria",
                            OrbitalPeriod = "184",
                            Population = "11000000",
                            RotationPeriod = "21",
                            SurfaceWater = "unknown",
                            Terrain = "swamps, lakes"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/35/",
                            Climate = "arid, temperate, tropical",
                            Created = new DateTime(2014, 12, 19, 17, 52, 13, 106, DateTimeKind.Utc),
                            Diameter = "18880",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 478, DateTimeKind.Utc),
                            Gravity = "1.56",
                            Name = "Malastare",
                            OrbitalPeriod = "201",
                            Population = "2000000000",
                            RotationPeriod = "26",
                            SurfaceWater = "unknown",
                            Terrain = "swamps, deserts, jungles, mountains"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/36/",
                            Climate = "temperate",
                            Created = new DateTime(2014, 12, 19, 18, 0, 40, 142, DateTimeKind.Utc),
                            Diameter = "10480",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 480, DateTimeKind.Utc),
                            Gravity = "0.9",
                            Name = "Dathomir",
                            OrbitalPeriod = "491",
                            Population = "5200",
                            RotationPeriod = "24",
                            SurfaceWater = "unknown",
                            Terrain = "forests, deserts, savannas"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/37/",
                            Climate = "temperate, arid, subartic",
                            Created = new DateTime(2014, 12, 20, 9, 46, 25, 740, DateTimeKind.Utc),
                            Diameter = "10600",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 481, DateTimeKind.Utc),
                            Gravity = "1",
                            Name = "Ryloth",
                            OrbitalPeriod = "305",
                            Population = "1500000000",
                            RotationPeriod = "30",
                            SurfaceWater = "5",
                            Terrain = "mountains, valleys, deserts, tundra"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/38/",
                            Climate = "unknown",
                            Created = new DateTime(2014, 12, 20, 9, 52, 23, 452, DateTimeKind.Utc),
                            Diameter = "unknown",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 483, DateTimeKind.Utc),
                            Gravity = "unknown",
                            Name = "Aleen Minor",
                            OrbitalPeriod = "unknown",
                            Population = "unknown",
                            RotationPeriod = "unknown",
                            SurfaceWater = "unknown",
                            Terrain = "unknown"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/39/",
                            Climate = "temperate, artic",
                            Created = new DateTime(2014, 12, 20, 9, 56, 58, 874, DateTimeKind.Utc),
                            Diameter = "14900",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 485, DateTimeKind.Utc),
                            Gravity = "1",
                            Name = "Vulpter",
                            OrbitalPeriod = "391",
                            Population = "421000000",
                            RotationPeriod = "22",
                            SurfaceWater = "unknown",
                            Terrain = "urban, barren"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/40/",
                            Climate = "unknown",
                            Created = new DateTime(2014, 12, 20, 10, 1, 37, 395, DateTimeKind.Utc),
                            Diameter = "unknown",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 487, DateTimeKind.Utc),
                            Gravity = "unknown",
                            Name = "Troiken",
                            OrbitalPeriod = "unknown",
                            Population = "unknown",
                            RotationPeriod = "unknown",
                            SurfaceWater = "unknown",
                            Terrain = "desert, tundra, rainforests, mountains"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/41/",
                            Climate = "unknown",
                            Created = new DateTime(2014, 12, 20, 10, 7, 29, 578, DateTimeKind.Utc),
                            Diameter = "12190",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 489, DateTimeKind.Utc),
                            Gravity = "unknown",
                            Name = "Tund",
                            OrbitalPeriod = "1770",
                            Population = "0",
                            RotationPeriod = "48",
                            SurfaceWater = "unknown",
                            Terrain = "barren, ash"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/42/",
                            Climate = "temperate",
                            Created = new DateTime(2014, 12, 20, 10, 12, 28, 980, DateTimeKind.Utc),
                            Diameter = "10120",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 491, DateTimeKind.Utc),
                            Gravity = "0.98",
                            Name = "Haruun Kal",
                            OrbitalPeriod = "383",
                            Population = "705300",
                            RotationPeriod = "25",
                            SurfaceWater = "unknown",
                            Terrain = "toxic cloudsea, plateaus, volcanoes"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/43/",
                            Climate = "temperate",
                            Created = new DateTime(2014, 12, 20, 10, 14, 48, 178, DateTimeKind.Utc),
                            Diameter = "unknown",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 493, DateTimeKind.Utc),
                            Gravity = "1",
                            Name = "Cerea",
                            OrbitalPeriod = "386",
                            Population = "450000000",
                            RotationPeriod = "27",
                            SurfaceWater = "20",
                            Terrain = "verdant"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/44/",
                            Climate = "tropical, temperate",
                            Created = new DateTime(2014, 12, 20, 10, 18, 26, 110, DateTimeKind.Utc),
                            Diameter = "15600",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 495, DateTimeKind.Utc),
                            Gravity = "1",
                            Name = "Glee Anselm",
                            OrbitalPeriod = "206",
                            Population = "500000000",
                            RotationPeriod = "33",
                            SurfaceWater = "80",
                            Terrain = "lakes, islands, swamps, seas"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/45/",
                            Climate = "unknown",
                            Created = new DateTime(2014, 12, 20, 10, 26, 5, 788, DateTimeKind.Utc),
                            Diameter = "unknown",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 497, DateTimeKind.Utc),
                            Gravity = "unknown",
                            Name = "Iridonia",
                            OrbitalPeriod = "413",
                            Population = "unknown",
                            RotationPeriod = "29",
                            SurfaceWater = "unknown",
                            Terrain = "rocky canyons, acid pools"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/46/",
                            Climate = "unknown",
                            Created = new DateTime(2014, 12, 20, 10, 28, 31, 117, DateTimeKind.Utc),
                            Diameter = "unknown",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 498, DateTimeKind.Utc),
                            Gravity = "unknown",
                            Name = "Tholoth",
                            OrbitalPeriod = "unknown",
                            Population = "unknown",
                            RotationPeriod = "unknown",
                            SurfaceWater = "unknown",
                            Terrain = "unknown"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/47/",
                            Climate = "arid, rocky, windy",
                            Created = new DateTime(2014, 12, 20, 10, 31, 32, 413, DateTimeKind.Utc),
                            Diameter = "unknown",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 500, DateTimeKind.Utc),
                            Gravity = "1",
                            Name = "Iktotch",
                            OrbitalPeriod = "481",
                            Population = "unknown",
                            RotationPeriod = "22",
                            SurfaceWater = "unknown",
                            Terrain = "rocky"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/48/",
                            Climate = "unknown",
                            Created = new DateTime(2014, 12, 20, 10, 34, 8, 249, DateTimeKind.Utc),
                            Diameter = "unknown",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 502, DateTimeKind.Utc),
                            Gravity = "unknown",
                            Name = "Quermia",
                            OrbitalPeriod = "unknown",
                            Population = "unknown",
                            RotationPeriod = "unknown",
                            SurfaceWater = "unknown",
                            Terrain = "unknown"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/49/",
                            Climate = "temperate",
                            Created = new DateTime(2014, 12, 20, 10, 48, 36, 141, DateTimeKind.Utc),
                            Diameter = "13400",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 504, DateTimeKind.Utc),
                            Gravity = "1",
                            Name = "Dorin",
                            OrbitalPeriod = "409",
                            Population = "unknown",
                            RotationPeriod = "22",
                            SurfaceWater = "unknown",
                            Terrain = "unknown"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/50/",
                            Climate = "temperate",
                            Created = new DateTime(2014, 12, 20, 10, 52, 51, 524, DateTimeKind.Utc),
                            Diameter = "unknown",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 506, DateTimeKind.Utc),
                            Gravity = "1",
                            Name = "Champala",
                            OrbitalPeriod = "318",
                            Population = "3500000000",
                            RotationPeriod = "27",
                            SurfaceWater = "unknown",
                            Terrain = "oceans, rainforests, plateaus"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/51/",
                            Climate = "unknown",
                            Created = new DateTime(2014, 12, 20, 16, 44, 46, 318, DateTimeKind.Utc),
                            Diameter = "unknown",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 508, DateTimeKind.Utc),
                            Gravity = "unknown",
                            Name = "Mirial",
                            OrbitalPeriod = "unknown",
                            Population = "unknown",
                            RotationPeriod = "unknown",
                            SurfaceWater = "unknown",
                            Terrain = "deserts"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/52/",
                            Climate = "unknown",
                            Created = new DateTime(2014, 12, 20, 16, 52, 13, 357, DateTimeKind.Utc),
                            Diameter = "unknown",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 510, DateTimeKind.Utc),
                            Gravity = "unknown",
                            Name = "Serenno",
                            OrbitalPeriod = "unknown",
                            Population = "unknown",
                            RotationPeriod = "unknown",
                            SurfaceWater = "unknown",
                            Terrain = "rainforests, rivers, mountains"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/53/",
                            Climate = "unknown",
                            Created = new DateTime(2014, 12, 20, 16, 54, 39, 909, DateTimeKind.Utc),
                            Diameter = "unknown",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 512, DateTimeKind.Utc),
                            Gravity = "unknown",
                            Name = "Concord Dawn",
                            OrbitalPeriod = "unknown",
                            Population = "unknown",
                            RotationPeriod = "unknown",
                            SurfaceWater = "unknown",
                            Terrain = "jungles, forests, deserts"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/54/",
                            Climate = "unknown",
                            Created = new DateTime(2014, 12, 20, 16, 56, 37, 250, DateTimeKind.Utc),
                            Diameter = "unknown",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 514, DateTimeKind.Utc),
                            Gravity = "unknown",
                            Name = "Zolan",
                            OrbitalPeriod = "unknown",
                            Population = "unknown",
                            RotationPeriod = "unknown",
                            SurfaceWater = "unknown",
                            Terrain = "unknown"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/55/",
                            Climate = "frigid",
                            Created = new DateTime(2014, 12, 20, 17, 27, 41, 286, DateTimeKind.Utc),
                            Diameter = "unknown",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 516, DateTimeKind.Utc),
                            Gravity = "unknown",
                            Name = "Ojom",
                            OrbitalPeriod = "unknown",
                            Population = "500000000",
                            RotationPeriod = "unknown",
                            SurfaceWater = "100",
                            Terrain = "oceans, glaciers"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/56/",
                            Climate = "temperate",
                            Created = new DateTime(2014, 12, 20, 17, 50, 47, 864, DateTimeKind.Utc),
                            Diameter = "unknown",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 517, DateTimeKind.Utc),
                            Gravity = "1",
                            Name = "Skako",
                            OrbitalPeriod = "384",
                            Population = "500000000000",
                            RotationPeriod = "27",
                            SurfaceWater = "unknown",
                            Terrain = "urban, vines"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/57/",
                            Climate = "temperate",
                            Created = new DateTime(2014, 12, 20, 17, 57, 47, 420, DateTimeKind.Utc),
                            Diameter = "13800",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 519, DateTimeKind.Utc),
                            Gravity = "1",
                            Name = "Muunilinst",
                            OrbitalPeriod = "412",
                            Population = "5000000000",
                            RotationPeriod = "28",
                            SurfaceWater = "25",
                            Terrain = "plains, forests, hills, mountains"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/58/",
                            Climate = "temperate",
                            Created = new DateTime(2014, 12, 20, 18, 43, 14, 49, DateTimeKind.Utc),
                            Diameter = "unknown",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 521, DateTimeKind.Utc),
                            Gravity = "1",
                            Name = "Shili",
                            OrbitalPeriod = "unknown",
                            Population = "unknown",
                            RotationPeriod = "unknown",
                            SurfaceWater = "unknown",
                            Terrain = "cities, savannahs, seas, plains"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/59/",
                            Climate = "arid, temperate, tropical",
                            Created = new DateTime(2014, 12, 20, 19, 43, 51, 278, DateTimeKind.Utc),
                            Diameter = "13850",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 523, DateTimeKind.Utc),
                            Gravity = "1",
                            Name = "Kalee",
                            OrbitalPeriod = "378",
                            Population = "4000000000",
                            RotationPeriod = "23",
                            SurfaceWater = "unknown",
                            Terrain = "rainforests, cliffs, canyons, seas"
                        },
                        new
                        {
                            Uri = "http://swapi.dev/api/planets/60/",
                            Climate = "unknown",
                            Created = new DateTime(2014, 12, 20, 20, 18, 36, 256, DateTimeKind.Utc),
                            Diameter = "unknown",
                            Edited = new DateTime(2014, 12, 20, 20, 58, 18, 525, DateTimeKind.Utc),
                            Gravity = "unknown",
                            Name = "Umbara",
                            OrbitalPeriod = "unknown",
                            Population = "unknown",
                            RotationPeriod = "unknown",
                            SurfaceWater = "unknown",
                            Terrain = "unknown"
                        });
                });

            modelBuilder.Entity("StarWarsUniverse.Domain.MoviePlanet", b =>
                {
                    b.HasOne("StarWarsUniverse.Domain.Movie", "Movie")
                        .WithMany("MoviePlanets")
                        .HasForeignKey("MovieUri")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWarsUniverse.Domain.Planet", "Planet")
                        .WithMany("MoviePlanets")
                        .HasForeignKey("PlanetUri")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
